"""
Tests for automation/multi_locator/step_mapping.py — testcase-step <->
automation-step traceability — and for the multi-dataset-independence
requirement (the same testcase's business steps must be identical
regardless of which persisted dataset variant is used).

See automation/multi_locator/step_mapping.py's own module docstring for
the disclosed, deterministic mapping heuristic and why today's entire
real testcase corpus (generated by the disclosed StubLLMClient) only
ever exercises the simple "N-1 concrete steps + 1 final observe step"
case in practice.
"""
from __future__ import annotations

import pytest

from automation.multi_locator.generate import build_multi_locator_artifact, resolve_source_automation_payload
from automation.multi_locator.schema import MultiLocatorGovernanceStatus
from automation.multi_locator.step_mapping import (
    TestcaseStepMapping,
    build_step_mapping,
    validate_full_coverage,
    validate_no_orphan_automation_steps,
    validate_order_preserved,
)
from automation.multi_locator.validate import govern_multi_locator_artifact
from automation.persist import BASE_DIR as AUTOMATION_BASE_DIR
from automation.schema import ActionType
from persistence.envelope import load_latest
import testcases.persist as tp


def _steps(*action_types):
    return [{"step_order": i + 1, "action_type": a} for i, a in enumerate(action_types)]


# ---------------------------------------------------------------------------
# build_step_mapping — unit
# ---------------------------------------------------------------------------

def test_single_testcase_step_maps_every_automation_step():
    steps = _steps(ActionType.NAVIGATE, ActionType.FILL, ActionType.CLICK)
    mappings = build_step_mapping(["Do the whole thing."], steps, has_assertions=True)
    assert len(mappings) == 1
    assert mappings[0].automation_step_orders == [1, 2, 3]
    assert mappings[0].maps_to_assertions is True


def test_two_testcase_steps_real_world_pattern():
    steps = _steps(ActionType.NAVIGATE, ActionType.FILL, ActionType.FILL, ActionType.CLICK)
    mappings = build_step_mapping(
        ["Perform the action described by the approved requirement.", "Observe the resulting system behavior."],
        steps, has_assertions=True,
    )
    assert len(mappings) == 2
    assert mappings[0].automation_step_orders == [1, 2, 3, 4]
    assert mappings[0].maps_to_assertions is False
    assert mappings[1].automation_step_orders == []
    assert mappings[1].maps_to_assertions is True


def test_richer_multi_step_testcase_splits_action_steps_in_order():
    """Demonstrates the mapping generalizes beyond the 2-generic-step
    real corpus, in case a future, richer testcase (e.g. a real live-LLM
    generation) supplies more specific steps."""
    steps = _steps(*([ActionType.NAVIGATE] + [ActionType.FILL] * 5 + [ActionType.CLICK]))
    business_steps = [
        "Navigate to the Demo Web Shop.",
        "Add the eligible product to the cart.",
        "Proceed to checkout.",
        "Enter the required billing information.",
        "Submit the checkout.",
        "Verify the expected result.",
    ]
    mappings = build_step_mapping(business_steps, steps, has_assertions=True)
    assert len(mappings) == 6
    # 7 real action steps split across 5 non-final business steps, in order
    all_action_orders = [m.automation_step_orders for m in mappings[:-1]]
    flattened = [o for chunk in all_action_orders for o in chunk]
    assert flattened == sorted(flattened) == list(range(1, 8))
    assert mappings[-1].maps_to_assertions is True
    assert mappings[-1].automation_step_orders == []


def test_no_action_steps_still_covers_every_testcase_step_without_fabricating_orders():
    mappings = build_step_mapping(["Step A.", "Step B.", "Observe."], [], has_assertions=True)
    assert len(mappings) == 3
    for m in mappings:
        assert m.automation_step_orders == []


# ---------------------------------------------------------------------------
# Validators
# ---------------------------------------------------------------------------

def test_full_coverage_passes_when_every_step_has_content_or_assertions():
    mappings = [
        TestcaseStepMapping(0, "a", [1, 2]),
        TestcaseStepMapping(1, "b", [], maps_to_assertions=True),
    ]
    result = validate_full_coverage(mappings, ["a", "b"])
    assert result["passed"] is True


def test_full_coverage_fails_when_a_step_has_neither():
    mappings = [
        TestcaseStepMapping(0, "a", [1, 2]),
        TestcaseStepMapping(1, "b", [], maps_to_assertions=False),
    ]
    result = validate_full_coverage(mappings, ["a", "b"])
    assert result["passed"] is False
    assert result["detail"]["missing_testcase_steps"] == [1]


def test_no_orphan_automation_steps_detects_an_unmapped_real_step():
    steps = _steps(ActionType.NAVIGATE, ActionType.FILL)
    mappings = [TestcaseStepMapping(0, "a", [1])]  # step_order 2 (FILL) never mapped
    result = validate_no_orphan_automation_steps(mappings, steps)
    assert result["passed"] is False
    assert result["detail"]["orphan_step_orders"] == [2]


def test_order_preserved_detects_a_regression():
    mappings = [
        TestcaseStepMapping(0, "a", [3, 4]),
        TestcaseStepMapping(1, "b", [1, 2]),  # regresses behind step 0's max
    ]
    result = validate_order_preserved(mappings)
    assert result["passed"] is False


def test_order_preserved_passes_for_ascending_chunks():
    mappings = [
        TestcaseStepMapping(0, "a", [1, 2]),
        TestcaseStepMapping(1, "b", [3, 4]),
    ]
    assert validate_order_preserved(mappings)["passed"] is True


# ---------------------------------------------------------------------------
# Governance integration: malformed step mappings are rejected
# ---------------------------------------------------------------------------

def test_governance_rejects_an_index_gap_in_stored_mappings():
    from automation.multi_locator.schema import MultiLocatorArtifact, StepLocatorCandidateSet, LocatorCandidate
    artifact = MultiLocatorArtifact(
        ml_automation_id="ML-X", source_automation_id="PW-X", testcase_id="TC-X",
        requirement_ids=["REQ-X"], test_data_set_id="TD-X",
        step_candidate_sets=[
            StepLocatorCandidateSet(1, "f", [LocatorCandidate(4, "STABLE_ATTRIBUTE", "#x", "src", "ref", "HIGH")]),
        ],
        testcase_step_mappings=[
            {"testcase_step_index": 0, "testcase_step_text": "a", "automation_step_orders": [1], "maps_to_assertions": False},
            {"testcase_step_index": 2, "testcase_step_text": "c", "automation_step_orders": [], "maps_to_assertions": True},  # gap at index 1
        ],
    )
    governed = govern_multi_locator_artifact(artifact)
    assert governed.governance_status == MultiLocatorGovernanceStatus.REJECTED
    assert any("TESTCASE_STEP_MAPPING_INDEX_GAP" in r for r in governed.reasons)


# ---------------------------------------------------------------------------
# Real, multi-dataset independence (real corpus)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def real_testcase_payload():
    payload = load_latest(tp.BASE_DIR, "TC-REQ-ACO-03-01")
    if payload is None:
        pytest.skip("Real corpus testcase TC-REQ-ACO-03-01 not present on disk in this environment")
    return payload


def test_same_testcase_two_datasets_identical_business_steps_distinct_ids(real_testcase_payload):
    payload_d1 = resolve_source_automation_payload("PW-TC-REQ-ACO-03-01-01", "TD-TC-REQ-ACO-03-01-01")
    payload_d2 = resolve_source_automation_payload("PW-TC-REQ-ACO-03-01-01", "TD-TC-REQ-ACO-03-01-02")

    artifact_d1 = build_multi_locator_artifact(payload_d1, "ML-STEPTEST-D01", testcase_payload=real_testcase_payload)
    artifact_d2 = build_multi_locator_artifact(payload_d2, "ML-STEPTEST-D02", testcase_payload=real_testcase_payload)

    # Business-step structure (the mapping) is identical -- only the
    # backing test_data_set_id and ml_automation_id differ.
    assert artifact_d1.testcase_step_mappings == artifact_d2.testcase_step_mappings
    assert artifact_d1.test_data_set_id != artifact_d2.test_data_set_id
    assert artifact_d1.ml_automation_id != artifact_d2.ml_automation_id

    field_order_d1 = [s.get("input_mapping") for s in payload_d1["steps"] if s.get("input_mapping")]
    field_order_d2 = [s.get("input_mapping") for s in payload_d2["steps"] if s.get("input_mapping")]
    assert field_order_d1 == field_order_d2
